insert into VDT_KHV_KeHoachVonNam_DuocDuyet_ChiTiet(
		iID_KeHoachVonNam_DuocDuyet_ChiTietID,
		iID_KeHoachVonNam_DuocDuyetID,
		iID_DuAnID,
		iID_MucID,
		iID_TieuMucID,
		iID_TietMucID,
		iID_NganhID,
		sTrangThaiDuAnDangKy,
		sGhiChu,
		LNS,
		L,
		K,
		M,
		TM,
		TTM,
		NG,
		fCapPhatTaiKhoBac,
		fCapPhatBangLenhChi,
		iID_LoaiCongTrinh,
		fGiaTriThuHoiNamTruocKhoBac,
		fGiaTriThuHoiNamTruocLenhChi,
		iID_Parent
	)
	select
		NEWID(),
		@iID_KePhanBoVonDonViL,
		pbvct.iID_DuAnID,
		pbvct.iID_MucID,
		pbvct.iID_TieuMucID,
		pbvct.iID_TietMucID,
		pbvct.iID_NganhID,
		pbvct.sTrangThaiDuAnDangKy,
		pbvct.sGhiChu,
		pbvct.LNS,
		pbvct.L,
		pbvct.K,
		pbvct.M,
		pbvct.TM,
		pbvct.TTM,
		pbvct.NG,
		isnull(pbvct.fCapPhatTaiKhoBac, 0),
		isnull(pbvct.fCapPhatBangLenhChi, 0),
		pbvct.iID_LoaiCongTrinh,
		isnull(pbvct.fGiaTriThuHoiNamTruocKhoBac, 0),
		isnull(pbvct.fGiaTriThuHoiNamTruocLenhChi, 0),
		pbvct.iID_KeHoachVonNam_DuocDuyet_ChiTietID
	from
		VDT_KHV_KeHoachVonNam_DuocDuyet_ChiTiet pbvct
	where pbvct.iID_KeHoachVonNam_DuocDuyetID = @iID_KePhanBoVonDonViF